resources:
  - name: springapp
    type: git
    source:
      uri: https://github.com/imnitin28/Maven_group_1.git
      branch: main

  - name: springapp-docker-repository
    type: docker-image
    source:
      email: ((docker-hub-email))
      username: ((docker-hub-username))
      password: ((docker-hub-password))
      repository: ((docker-hub-username))/((docker-hub-repo-name))


jobs:
  - name: test
    public: true

    plan:
      - get: springapp
        trigger: true
      - task: mvn-test
        file: "./Maven_Group_1/concourse_ci/tasks/maven-test.yml"

  - name: package
    public: true
    serial: true
    plan:
      - get: springapp
        trigger: true
        passed: [test]
      - task: mvn-package
        file: "springapp/concourse_ci/tasks/maven-package.yml"
      - put: springapp-docker-repository
        params:
          build: springapp-out
    
