fly ---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: maven
    tag: 3.6.0-jdk-8-alpine

inputs:
  - name: springapp

run:
  path: "mvn"
  args:
    - -f
    - springapp/pom.xml
    - clean
    - package
    
outputs:
  - name: springapp-out
    path: springapp
